### ISSUE TITLE
Pagination Styling has Disappeared

### ISSUE THREAD

**Issue by jacobdaddario** [excid3/madmin#108]
Noticed this while working on a feature PR. It looks like the styles themselves went missing. The pagination buttons still have the proper classes assigned to them. I'll keep an eye out and see if I can find where in the commit history that these went missing.

**Comment by jitingcn** [comment]
I think this is caused by pagy generates the pagination bar with a set of default classes, but it does not have any styles by default.  
The purpose of this behavior is convenient for users to customize styles.

Pagy's documentation has mentioned how to add a set of default styles to style libraries such as [tailwind](https://ddnexus.github.io/pagy/extras/tailwind), but unfortunately, seem like we need postcss preprocessor to use it.

Consider if we want to add support like dark mode in the future, using some gem to generate styles may provide benefits, but it may also bring other customization and compatibility issues, and complicates the assets precompile process.

**Comment by excid3** [comment]
I think it might be easiest if we render a custom pagy template instead: 
https://ddnexus.github.io/pagy/how-to#using-templates&gsc.tab=0

We can take this, add our Tailwind styles to it, and be good to go:
https://github.com/ddnexus/pagy/blob/master/lib/templates/nav.html.erb
